"""empty message

Revision ID: 08376fd970af
Revises: bd407fb50e17
Create Date: 2025-05-21 23:05:37.232183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08376fd970af'
down_revision = 'bd407fb50e17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant_batch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('yield_amount_unit', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant_batch', schema=None) as batch_op:
        batch_op.drop_column('yield_amount_unit')

    # ### end Alembic commands ###
