"""empty message

Revision ID: 62125f923018
Revises: 3a00893d49cc
Create Date: 2025-01-23 23:31:55.388920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62125f923018'
down_revision = '3a00893d49cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_available_online', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('is_available_online')

    # ### end Alembic commands ###
