"""job application and employee training fields

Revision ID: 75a09d475c7c
Revises: 2881ac91a7fd
Create Date: 2026-03-30 19:34:53.233453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75a09d475c7c'
down_revision = '2881ac91a7fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('applicant_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('applicant_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('applicant_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('cover_letter', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_application', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('cover_letter')
        batch_op.drop_column('applicant_phone')
        batch_op.drop_column('applicant_email')
        batch_op.drop_column('applicant_name')

    # ### end Alembic commands ###
