"""empty message

Revision ID: a8a3471e23d9
Revises: 53d77c853486
Create Date: 2024-11-30 00:43:48.831959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8a3471e23d9'
down_revision = '53d77c853486'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('plan_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('plan_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
