"""empty message

Revision ID: edfa5b0ec923
Revises: ead33a0cce8c
Create Date: 2025-01-01 13:46:47.654845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edfa5b0ec923'
down_revision = 'ead33a0cce8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('date_sold', sa.Date(), nullable=False),
    sa.Column('quantity_sold', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales_history')
    # ### end Alembic commands ###
